# Generated by Django 5.0.7 on 2024-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='training',
            field=models.CharField(default='default_value', max_length=30),
        ),
    ]
